name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_kind:
        type: choice
        description: The type of release.
        default: prerelease
        required: true
        options:
          - prerelease
          - start-rc
          - stable
      publish:
        description: "True to publish release to git, vpm. if false, this creates release asset only"
        type: boolean
        required: false

env:
  PKG_NAME: NDMFDeform
  SOMETHING_RELEASER_SEMVER: 1

concurrency:
  group: publish
  cancel-in-progress: true

permissions: write-all

jobs:
  create-release:
    runs-on: ubuntu-latest
    environment:
      name: actions-github-app
    outputs:
      version: ${{ steps.update-version.outputs.version }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          submodules: recursive
      - uses: anatawa12/something-releaser@v2
      - uses: snow-actions/git-config-user@v1.0.0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true

      - name: Check release is public
        if: github.event.inputs.release_kind == 'stable'
        run: |
          if [[ "$(jq '.private == true' < package.json)" == "true" ]]; then
            echo "package.json is private"
            exit 255
          fi
      - name: Check release is public
        run: |
          if [[ "$(jq '.["private-beta"] == true' < package.json)" == "true" ]]; then
            echo "package.json is private-beta"
            exit 255
          fi
      
      - name: Update Version Name
        id: update-version
        run: |
          # set version name in properties file
          case "$RELEASE_KIND_IN" in
            "prerelease" )
              set-version "$(version-next "$(get-version)")"
              gh-export-variable PRERELEASE true
              ;;
            "start-rc" )
              set-version "$(version-set-channel "$(get-version)" rc)"
              gh-export-variable PRERELEASE true
              ;;
            "stable" )
              set-version "$(version-set-channel "$(get-version)" stable)"
              gh-export-variable PRERELEASE false
              ;;
            * )
              echo "invalid release kind: $RELEASE_KIND_IN"
              exit 255
              ;;
          esac

          case "$GITHUB_REF_NAME" in
            master | master-* | main )
              echo "head is master or master-* or main"
              ;;
            * )
              echo "invalid release kind: $RELEASE_KIND_IN is not allowd for $GITHUB_REF_NAME"
              exit 255
              ;;
          esac

          gh-export-variable VERSION "$(get-version)"
          gh-set-output version "$(get-version)"
        env:
          RELEASE_KIND_IN: ${{ github.event.inputs.release_kind }}

      # region changelog
      - name: Create Changelog
        id: changelog
        uses: anatawa12/sh-actions/changelog/prepare-release@master
        with:
          version: ${{ env.VERSION }}
          prerelease: ${{ env.PRERELEASE }}
          tag-prefix: v
          prerelease-note-heading: |
            Version ${{ env.VERSION }}
            ---
            
            Add to VCC/ALCOM from [here][installer for this].

            [installer for this]: https://c-colloid.github.io/NDMFDeform/.redirect.html
            
            **This is SNAPSHOT, not a stable release. make sure this may have many bugs.**
          release-note-heading: |
            Version ${{ env.VERSION }}
            ---
            
            Add to VCC/ALCOM from [here][installer for this].

            [installer for this]: https://c-colloid.github.io/NDMFDeform/.redirect.html
      - name: Upload CHANGELOG.md
        if: ${{ !fromJSON(env.PRERELEASE) }}
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG
          path: CHANGELOG.md
      - name: Upload CHANGELOG-PRERELEASE.md
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG-PRERELEASE
          path: CHANGELOG-PRERELEASE.md
      - run: cp "${{ steps.changelog.outputs.release-note }}" release-note.md
      - name: Upload release note
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: release-note.md
      - run: rm release-note.md
      # endregion changelog

      - name: Commit & tag version
        if: ${{ inputs.publish }}
        run: |
          git tag "v$VERSION"

      # region building
      - name: Prepare build folder
        run: mkdir build

      # refion unitypackage release
      - name: Set Environment Variables
        run: |
          echo "unityPackage=build/$PKG_NAME-v$VERSION.unitypackage" >> $GITHUB_ENV

      - name: Create UnityPackage
        uses: anatawa12/sh-actions/create-unitypackage@master
        with:
          output-path: ${{ env.unityPackage }}
          package-path: "./"
          path-prefix: "Packages/jp.colloid.lipsyncsetter/"
      #endregion unitypackage release

      # region vpm release
      - name: Build VPM release
        run: |
          zip -r "build/$PKG_NAME-v$VERSION.zip" . -x 'build*' '.*' 'Test~/*'
      - name: Upload VPM release
        uses: actions/upload-artifact@v3
        with:
          name: vpm-package
          path: build/${{ env.PKG_NAME }}-${{ env.VERSION }}.zip
      # endregion vpm release
      
      # endregion building

      - name: Publish Release
        if: ${{ inputs.publish }}
        run: |
          git push && git push origin "v$VERSION" -f

      - name: Publish release to github
        if: ${{ inputs.publish }}
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_NOTE: ${{ steps.changelog.outputs.release-note }}
        shell: bash
        run: |
          sleep 1
          # upload release assets
          gh release create "v$VERSION" \
            -F "$RELEASE_NOTE" \
            ${{ fromJSON(env.PRERELEASE) && '--prerelease' || '' }} \
            "build/$PKG_NAME-v$VERSION.unitypackage" \
            "build/$PKG_NAME-v$VERSION.zip" \
            "package.json" \

      - name: Restore package.json
        run: git restore --staged --worktree package.json

      - name: prepare next release & push
        if: inputs.publish && !fromJSON(env.PRERELEASE)
        run: |
          VERSION="$(version-next "$(get-version)")"
          set-version "$(version-set-channel "$VERSION" beta 0)"
          git commit -am "chore: prepare for next version: $VERSION"
          git push && git push --tags

  publish-vpm:
    uses: c-colloid/LipSyncSetter/.github/workflows/release-VPM.yml@main
    needs: create-release
    if: inputs.publish
    with:
      tag: v${{ needs.create-release.outputs.version }}
